---
- name: Ensure httpd package is present
  yum:
   name: "{{ httpdversion }}"
   state: present

- name: Ensure latest index.html file is present
  copy:
   src: files/index.html
   dest: /var/www/html/

- name: Ensure httpd is started
  service:
   name: httpd
   state: started
